modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/Stonks/issues"
license="MIT"

[[mods]]
modId="stonks"
logoFile="stonks.png"
version="${file.jarVersion}"
displayName="Stonks"
displayURL="https://www.curseforge.com/minecraft/mc-mods/stonks"
authors="Mrbysco"
description='''
Villager stonks!
'''
[[dependencies.stonks]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.stonks]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.70-beta,)"
ordering="NONE"
side="BOTH"
[[mixins]]
config="stonks.mixins.json"